apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  labels:
    qcloud-app: dbjob-cron
  name: dbjob-cron
  namespace: $NAMESPACE
spec:
  schedule: "30 23 * * *"
  jobTemplate:
    metadata:
      annotations:
        cloud.tencent.com/volume-configmap-info: '[]'
      labels:
        qcloud-app: dbjob-cron
    spec:
      template:
        spec:
          containers:
          - args:
            - su
            - root
            - -c
            - /bin/bash -x /mnt/backupscript/pg_backup_rotated.sh      
            env:
            - name: POSTGRES_USER
              value: odoo
            - name: POSTGRES_PASSWORD
              value: odoo
            - name: PGPASSWORD
              value: odoo
            image: postgres:9.5
            imagePullPolicy: Always
            name: dbjob
            resources:
              limits:
                cpu: 500m
                memory: 512Mi
              requests:
                cpu: 250m
                memory: 256Mi
            securityContext:
              privileged: false
            terminationMessagePath: /dev/termination-log
            volumeMounts:
            - mountPath: /mnt/data-dir
              name: data-dir
            - mountPath: /mnt/backup
              name: backup
            - mountPath: /mnt/backupscript
              name: backupscript                  
          dnsPolicy: ClusterFirst
          imagePullSecrets:
          - name: qcloudregistrykey
          restartPolicy: OnFailure
          securityContext: {}
          serviceAccountName: ""
          terminationGracePeriodSeconds: 30
          volumes:
          - name: data-dir
            nfs:
              path: /odoo-saas/$NAMESPACE/data-dir
              server: 10.0.3.13
          - name: backup
            nfs:
              path: /$NAMESPACE
              server: 10.0.4.9
          - name: backupscript
            nfs:
              path: /odoo-saas/dbbackup
              server: 10.0.3.13
